CREATE TABLE topicos (
id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
titulo VARCHAR(255) NOT NULL,
mensagem TEXT NOT NULL,
data_criacao DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
status VARCHAR(50) NOT NULL,
autor_id BIGINT,
curso_id BIGINT,
FOREIGN KEY (autor_id) REFERENCES usuarios(id),
FOREIGN KEY (curso_id) REFERENCES cursos(id)
);